package com.zmb.bi.persist.po;

public class CarWashInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash_info.id
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash_info.uid
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash_info.car_id
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash_info.car_plate_no
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    private String carPlateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash_info.car_brand
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    private String carBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash_info.car_model
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    private String carModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash_info.car_color
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    private String carColor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash_info.id
     *
     * @return the value of car_wash_info.id
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash_info.id
     *
     * @param id the value for car_wash_info.id
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash_info.uid
     *
     * @return the value of car_wash_info.uid
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash_info.uid
     *
     * @param uid the value for car_wash_info.uid
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash_info.car_id
     *
     * @return the value of car_wash_info.car_id
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash_info.car_id
     *
     * @param carId the value for car_wash_info.car_id
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash_info.car_plate_no
     *
     * @return the value of car_wash_info.car_plate_no
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public String getCarPlateNo() {
        return carPlateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash_info.car_plate_no
     *
     * @param carPlateNo the value for car_wash_info.car_plate_no
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public void setCarPlateNo(String carPlateNo) {
        this.carPlateNo = carPlateNo == null ? null : carPlateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash_info.car_brand
     *
     * @return the value of car_wash_info.car_brand
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public String getCarBrand() {
        return carBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash_info.car_brand
     *
     * @param carBrand the value for car_wash_info.car_brand
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand == null ? null : carBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash_info.car_model
     *
     * @return the value of car_wash_info.car_model
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public String getCarModel() {
        return carModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash_info.car_model
     *
     * @param carModel the value for car_wash_info.car_model
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public void setCarModel(String carModel) {
        this.carModel = carModel == null ? null : carModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash_info.car_color
     *
     * @return the value of car_wash_info.car_color
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public String getCarColor() {
        return carColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash_info.car_color
     *
     * @param carColor the value for car_wash_info.car_color
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    public void setCarColor(String carColor) {
        this.carColor = carColor == null ? null : carColor.trim();
    }
}