package com.zmb.bi.persist.po;

import java.util.Date;

public class ChannelInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.id
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.channel_code
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private Integer channelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.channel_name
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.organization
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private String organization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.inner_channel_code
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private String innerChannelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.target_sys_id
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private Integer targetSysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.salt
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.status
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.create_by
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.create_dt
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.update_dt
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private Date updateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_info.update_by
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.id
     *
     * @return the value of channel_info.id
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.id
     *
     * @param id the value for channel_info.id
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.channel_code
     *
     * @return the value of channel_info.channel_code
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public Integer getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.channel_code
     *
     * @param channelCode the value for channel_info.channel_code
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setChannelCode(Integer channelCode) {
        this.channelCode = channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.channel_name
     *
     * @return the value of channel_info.channel_name
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.channel_name
     *
     * @param channelName the value for channel_info.channel_name
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.organization
     *
     * @return the value of channel_info.organization
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.organization
     *
     * @param organization the value for channel_info.organization
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.inner_channel_code
     *
     * @return the value of channel_info.inner_channel_code
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public String getInnerChannelCode() {
        return innerChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.inner_channel_code
     *
     * @param innerChannelCode the value for channel_info.inner_channel_code
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setInnerChannelCode(String innerChannelCode) {
        this.innerChannelCode = innerChannelCode == null ? null : innerChannelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.target_sys_id
     *
     * @return the value of channel_info.target_sys_id
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public Integer getTargetSysId() {
        return targetSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.target_sys_id
     *
     * @param targetSysId the value for channel_info.target_sys_id
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setTargetSysId(Integer targetSysId) {
        this.targetSysId = targetSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.salt
     *
     * @return the value of channel_info.salt
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.salt
     *
     * @param salt the value for channel_info.salt
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.status
     *
     * @return the value of channel_info.status
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.status
     *
     * @param status the value for channel_info.status
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.create_by
     *
     * @return the value of channel_info.create_by
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.create_by
     *
     * @param createBy the value for channel_info.create_by
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.create_dt
     *
     * @return the value of channel_info.create_dt
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.create_dt
     *
     * @param createDt the value for channel_info.create_dt
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.update_dt
     *
     * @return the value of channel_info.update_dt
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.update_dt
     *
     * @param updateDt the value for channel_info.update_dt
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_info.update_by
     *
     * @return the value of channel_info.update_by
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_info.update_by
     *
     * @param updateBy the value for channel_info.update_by
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}