package com.zmb.bi.persist.po;

import java.util.Date;

public class TaskFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.id
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.task_code
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    private String taskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.task_name
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.exec_status
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    private Integer execStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_flow.task_dt
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    private Date taskBeginDt;
    
    private Date taskEndDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_flow.id
     *
     * @return the value of task_flow.id
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_flow.id
     *
     * @param id the value for task_flow.id
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_flow.task_code
     *
     * @return the value of task_flow.task_code
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_flow.task_code
     *
     * @param taskCode the value for task_flow.task_code
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_flow.task_name
     *
     * @return the value of task_flow.task_name
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_flow.task_name
     *
     * @param taskName the value for task_flow.task_name
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_flow.exec_status
     *
     * @return the value of task_flow.exec_status
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    public Integer getExecStatus() {
        return execStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_flow.exec_status
     *
     * @param execStatus the value for task_flow.exec_status
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    public void setExecStatus(Integer execStatus) {
        this.execStatus = execStatus;
    }

	public Date getTaskBeginDt() {
		return taskBeginDt;
	}

	public void setTaskBeginDt(Date taskBeginDt) {
		this.taskBeginDt = taskBeginDt;
	}

	public Date getTaskEndDt() {
		return taskEndDt;
	}

	public void setTaskEndDt(Date taskEndDt) {
		this.taskEndDt = taskEndDt;
	}

}