package com.zmb.bi.dao;

import com.zmb.bi.persist.po.CarWashInfo;

public interface CarWashInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash_info
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash_info
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    int insert(CarWashInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash_info
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    int insertSelective(CarWashInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash_info
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    CarWashInfo selectByPrimaryKey(Integer id);
    
    /**
	 * 根据车牌号，查询车辆用户总数
	 * @param		:	carPlateNo		车牌号
	 * @return		:	int				查询到的个数
	 * @comments	:	
	 */
    int selectByCarPlateNoCount(String carPlateNo);
    
    /**
	 * 根据UID查询车辆用户信息
	 * @param		:	uid				用户ID
	 * @return		:	CarWashInfo		车辆用户信息
	 * @comments	:	
	 */
    CarWashInfo selectByUid(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash_info
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    int updateByPrimaryKeySelective(CarWashInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash_info
     *
     * @mbg.generated Fri Jun 23 11:45:24 CST 2017
     */
    int updateByPrimaryKey(CarWashInfo record);
}