package com.zmb.bi.dao;

import java.util.List;

import com.zmb.bi.persist.po.SysParam;

public interface SysParamDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int insert(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int insertSelective(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    SysParam selectByPrimaryKey(Integer id);

    /**
	 * 全部系统参数查询
	 * @param		:	
	 * @return		:	List<SysParam>		全部系统参数列表
	 * @comments	:	
	 */
    List<SysParam> selectAll();
    
    /**
	 * 全部可用系统参数查询
	 * @param		:	
	 * @return		:	List<SysParam>		全部可用系统参数列表
	 * @comments	:	
	 */
    List<SysParam> selectAvailableList();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int updateByPrimaryKeySelective(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int updateByPrimaryKey(SysParam record);
}