package com.zmb.bi.dao;

import com.zmb.bi.persist.po.Task;

public interface TaskDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    Task selectByPrimaryKey(Integer id);
    
    /**
	 * 当前可用任务查询
	 * @param		:	
	 * @return		:	Task		当前可用任务
	 * @comments	:	
	 */
    Task selectAvailableTaskList();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Jun 19 16:06:15 CST 2017
     */
    int updateByPrimaryKey(Task record);
}