package com.zmb.bi.dao;

import java.util.List;

import com.zmb.bi.persist.po.WhiteList;

public interface WhiteListDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int insert(WhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int insertSelective(WhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    WhiteList selectByPrimaryKey(Integer id);

    /**
	 * 全部白名单查询
	 * @param		:	
	 * @return		:	List<WhiteList>		全部白名单列表
	 * @comments	:	
	 */
    List<WhiteList> selectAll();
    
    /**
	 * 全部可用白名单查询
	 * @param		:	
	 * @return		:	List<WhiteList>		全部可用白名单列表
	 * @comments	:	
	 */
    List<WhiteList> selectAvailableList();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int updateByPrimaryKeySelective(WhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Wed Aug 02 18:36:40 CST 2017
     */
    int updateByPrimaryKey(WhiteList record);
}